[package]
name = "day-19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5"
itertools = "0.10"
nalgebra = "0.29"
regex = "1"
thiserror = "1"
