[package]
name = "day-08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2"
bitvec = "0.22"
color-eyre = "0.5"
itertools = "0.10"
